version: "3.8"

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: db
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
    command: sh -c "npm install && npm run dev"

  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app

    stdin_open: true
    tty: true

volumes:
  db-data: {}
